name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout LIMPO da branch que acabou de receber push
      - name: Checkout branch
        uses: actions/checkout@v4

      # 2. Setup do builder (buildx = suporta cache, multiplataforma se você quiser no futuro)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login no Docker Hub usando secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Decide a tag com base na branch
      - name: Set image tag
        id: vars
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT


      # 5. Construir a imagem
      #    OBS: ajuste "ipti/sua-imagem" pro nome REAL do repositório no Docker Hub
      - name: Build image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_REPO }}:${{ steps.vars.outputs.TAG }} \
            .

      # 6. Publicar no Docker Hub
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_REPO }}:${{ steps.vars.outputs.TAG }}
